### ISSUE TITLE
ModuleNotFoundError: No module named 'wtforms.compat'

### ISSUE THREAD

**Issue by berry2012** [aws-samples/airflow-for-amazon-eks-blog#4]
+ ./tmp/airflow-test-env-init.sh
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 70, in <module>
    from airflow.www.app import (cached_app, create_app)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 37, in <module>
    from airflow.www.blueprints import routes
  File "/usr/local/lib/python3.6/site-packages/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/usr/local/lib/python3.6/site-packages/airflow/www/utils.py", line 32, in <module>
    from wtforms.compat import text_type
ModuleNotFoundError: No module named 'wtforms.compat'

**Comment by berry2012** [comment]
Solution....
In the Dockerfile, add 
pip3 install wtforms==2.3.3

**Comment by berry2012** [comment]
Solved
